### ISSUE TITLE
PG Permision denied on setup_hstore migration

### ISSUE THREAD

**Issue by guidomb** [diogob/activerecord-postgres-hstore#99]
When I run the setup_hstore migration I get the following error

``` bash
==  SetupHstore: migrating ====================================================
-- execute("CREATE EXTENSION IF NOT EXISTS hstore")
rake aborted!
PG::Error: ERROR:  permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS hstore
/vagrant/db/migrate/20130415193403_setup_hstore.rb:3:in `up'
Tasks: TOP => db:migrate:up
(See full trace by running task with --trace)
```

I am using Postgres 9.1 on Ubuntu 12.04 LTS installed via apt-get. I have installed the postgresql-contrib package.

The only way a can get hstore to work is by executing the following command

``` bash
sudo su postgres -c "psql MY_DATABASE -c 'CREATE EXTENSION hstore;'"
```

Super database user is a requirement for this gem to work?

To setup my PostgreSQL database I ran the following  commands

``` bash
sudo su postgres
psql -c "create user foo with password 'foobar'"
psql -c "create database my_database_development owner foo"
psql -c "create database my_database_test owner foo"
psql -c "alter user foo createdb"
```

and this is my database.yml

``` yaml
development:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5
  timeout: 5000
  username: foo
  password: foobar
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: my_database_test
  pool: 5
  timeout: 5000
  username: foo
  password: foobar
  host: localhost
```
